blank_issues_enabled: true
contact_links:
  - name: NixOS Manual
    url: https://nixos.org/manual/nixos/stable/
    about: Official NixOS configuration manual
  - name: Home Manager Options
    url: https://nix-community.github.io/home-manager/options.xhtml
    about: Home Manager configuration options reference
  - name: NixOS Package Search
    url: https://search.nixos.org/packages
    about: Search for available NixOS packages
  - name: Nix Language Guide
    url: https://nix.dev/manual/nix/2.28/language/
    about: Nix language syntax and features
